### ISSUE TITLE
iojs 相关文章可以相互发布

### ISSUE THREAD

**Issue by fengmk2** [jieio/du#3]
现在 iojs-cn 每周都会将 weekly news 翻译，是否可以通过 解 io 的渠道发布出去？

而解 io的 iojs 相关文章，是否也能发布到 http://cn.iojs.org/ 这个 blog 中？

**Comment by fengmk2** [comment]
像 @goddyZhao 这篇文章非常适合发布在 iojs 中文社区 https://github.com/jieio/du/blob/master/posts/2015-03-09-reconciliation-of-node-and-io-by-goddyzhao.md

**Comment by goddyZhao** [comment]
当然，@fengmk2，你觉得怎么样操作比较方面呢？

**Comment by fengmk2** [comment]
一样的，相互发 pr 合并就行，哈哈，我们的做法跟 jieio 一样的。来吧，提交 pr！我也将3.6的 weekly news 提交到这边。

**Comment by fraserxu** [comment]
线下其他JS聚会可以通过什么渠道提交呢?

**Comment by goddyZhao** [comment]
@fengmk2 ok， cool~ 就这么搞吧！社区要团结一致~ :smiley:

**Comment by fraserxu** [comment]
被忽略了... :(

**Comment by goddyZhao** [comment]
@fraserxu sorry，miss掉了你的message，reopen了！没理解你的意思，“线下其他JS聚会可以通过什么渠道提交呢?”

**Comment by fraserxu** [comment]
比如说我近期要举办一次线下的JavaScript聚会, 可以通过某种渠道提交到解io?

因为目前我们在社区的影响力有限, 想要让更多的人知道我们的活动比较困难.

**Comment by goddyZhao** [comment]
@fraserxu 懂了！这个你可以直接将活动内容介绍整理成markdown+原文链接（如果有网页），pr到这里就可以了，我会安排发布到公众号的！

**Comment by JacksonTian** [comment]
@fraserxu 参见 https://github.com/cnodejs/nodeparty/issues/15

**Comment by fraserxu** [comment]
@goddyZhao @JacksonTian 好的, 单次活动就要做一篇单独的post吗? 是不是可以做个聚合类的比较好.

比如说周刊或月刊形式, 集中发布一周内或者一月内的主要线下活动预告, 这样可能更好的**凝聚**社区力量.

**Comment by JacksonTian** [comment]
单次活动发一个issue。其他地方宣传的时候我们给链接就好。

现在估计没那么多活动来预告。

**Comment by fraserxu** [comment]
@JacksonTian 如何理解"其他地方"? 

如果近期内活动少就单次发一篇, 如果刚好有比较多就可以整合成一篇.

我的理解是解io是一个国内范围的, 所以大大小小的活动应该还是有一些的.

**Comment by JacksonTian** [comment]
昂。。我说的不是jie.io，是NodeParty，我们开启了合作方式。参见我的链接。

**Comment by fraserxu** [comment]
哈哈哈. 可是我们活动不一定关于Node. 经常会是前端相关的... 当然还有iojs. 233333

**Comment by JacksonTian** [comment]
js相关即可。不是全前端的就可以。

**Comment by goddyZhao** [comment]
解IO不局限JS，都可以！
