### ISSUE TITLE
稿酬付费

### ISSUE THREAD

**Issue by JacksonTian** [jieio/du#5]
为了吸引更多人来写作，有必要弄稿酬，促进良性循环。

**Comment by goddyZhao** [comment]
那是不是要付费阅读或者找赞助商？ :smile:

**Comment by JacksonTian** [comment]
发招聘和广告就收费呀！

**Comment by goddyZhao** [comment]
嗯！先运营一段时间吧，多帮忙推推呀，V8哥。要不要来个V8系列的，讲讲如何优化node应用啥的？

**Comment by iwillwen** [comment]
@goddyzhao 你家產品不就是招聘相關麼？
廣告有必要收費。我要不要來個JavaScript優化或者21天精通Koa開發什麼的呢？

**Comment by goddyZhao** [comment]
@iwillwen 速度来啊
